"""Writes Data/QuestDetails.lua: per-quest details shown in the addon's quest inspector
(objectives, quest giver / turn-in with coordinates, quest type, XP, reputation and item rewards)."""
import os
import re

import luatable

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "Data", "QuestDetails.lua")

# QuestieDB quest fields
REQ_LEVEL, OBJECTIVES_TEXT, STARTED_BY, FINISHED_BY, REP_REWARD = 4, 8, 2, 3, 26
PRE_GROUP, PRE_SINGLE = 12, 13
# NPC fields
NPC_NAME, NPC_SPAWNS, NPC_ZONE, NPC_SUBNAME = 1, 7, 9, 14
# Object fields
OBJ_NAME, OBJ_SPAWNS, OBJ_ZONE = 1, 4, 5
# Item fields
ITEM_NAME, ITEM_QUEST_REWARDS = 1, 6

# Quest tags (same IDs as the game's QuestTag enum)
TAG_ELITE, TAG_PVP, TAG_RAID, TAG_DUNGEON = 1, 41, 62, 81
RAID_AREAS = {1977, 2159, 2677, 2717, 3428, 3429, 3456}
BATTLEGROUND_AREAS = {2597, 3277, 3358}
KEEP_TAGS = {TAG_ELITE, TAG_PVP, TAG_RAID, TAG_DUNGEON, 84}  # 84 = escort

# Tag conditions in Questie's corrections file that hold for Classic Era (and so for Forever).
ERA_CONDITIONS = {"", "Expansions.Current == Expansions.Era and", "Expansions.Current <= Expansions.Wotlk and",
                  "Expansions.Current < Expansions.Cata and", "Expansions.Current <= Expansions.Tbc and"}

GIVER_NPC, GIVER_OBJECT, GIVER_ITEM = 1, 2, 3


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "") + '"'


def load_long_table(text, name):
    return luatable.parse(luatable.extract_long_strings(text)[name])


def load_tags(text):
    tags = {}
    start = text.index("questTagCorrections = {")
    end = text.index("\n    }", start)
    for m in re.finditer(r"^\s*\[(\d+)\]\s*=\s*(.*?)\{(\d+),\s*l10n", text[start:end], re.M):
        if m.group(2).strip() in ERA_CONDITIONS:
            tags[int(m.group(1))] = int(m.group(3))
    return tags


def load_xp(text):
    body = text[text.index("QuestXP.db = ") + len("QuestXP.db = "):]
    body = body[:body.index("\n}") + 2]
    return {qid: luatable.as_list(v) for qid, v in luatable.parse(body).items()}


def id_list(value):
    return [v for v in luatable.as_list(value) or [] if isinstance(v, int)]


def first_ids(value, index):
    group = (value or {}).get(index) or {}
    return [v for v in luatable.as_list(group) or [] if isinstance(v, int)]


def write(ctx, fetch, used):
    quests = ctx["quests"]
    resolve_zone = ctx["resolve_zone"]
    area_names, area_to_map, map_to_area = ctx["area_names"], ctx["area_to_map"], ctx["map_to_area"]
    dungeons = ctx["dungeons"]

    npcs = load_long_table(fetch("npcs"), "QuestieDB.npcData")
    objects = load_long_table(fetch("objects"), "QuestieDB.objectData")
    items = load_long_table(fetch("items"), "QuestieDB.itemData")
    tags = load_tags(fetch("tags"))
    xp = load_xp(fetch("xp"))

    rewards = {}
    for item_id, item in items.items():
        for qid in luatable.as_list(item.get(ITEM_QUEST_REWARDS)) or []:
            if qid in used:
                rewards.setdefault(qid, []).append(item_id)

    used_npcs, used_objects, used_items, used_areas = {}, {}, {}, set()

    def location(spawns, zone_hint):
        """(areaID, x, y) of the first spawn, preferring the record's main zone."""
        if not spawns:
            return None
        area = zone_hint if zone_hint in spawns else sorted(spawns)[0]
        coords = luatable.as_list(spawns[area]) or []
        x, y = (luatable.as_list(coords[0]) or [-1, -1])[:2] if coords else (-1, -1)
        if x is None or y is None or x < 0 or y < 0:
            x = y = None
        return area, x, y

    def giver(entry, allow_items):
        for kind, index in ((GIVER_NPC, 1), (GIVER_OBJECT, 2)) + (((GIVER_ITEM, 3),) if allow_items else ()):
            for gid in first_ids(entry, index):
                if kind == GIVER_NPC and gid in npcs:
                    n = npcs[gid]
                    used_npcs[gid] = (n.get(NPC_NAME), n.get(NPC_SUBNAME), location(n.get(NPC_SPAWNS), n.get(NPC_ZONE)))
                    return kind, gid
                if kind == GIVER_OBJECT and gid in objects:
                    o = objects[gid]
                    used_objects[gid] = (o.get(OBJ_NAME), location(o.get(OBJ_SPAWNS), o.get(OBJ_ZONE)))
                    return kind, gid
                if kind == GIVER_ITEM and gid in items:
                    used_items[gid] = items[gid].get(ITEM_NAME)
                    return kind, gid
        return 0, 0

    def tag_of(qid, q):
        tag = tags.get(qid)
        if tag in KEEP_TAGS:
            return tag
        area = resolve_zone(q.get(17) or 0)
        if area in BATTLEGROUND_AREAS:
            return TAG_PVP
        if area in RAID_AREAS:
            return TAG_RAID
        if area in dungeons:
            return TAG_DUNGEON
        return 0

    lines = [
        "-- AUTO GENERATED by tools/generate_data.py from the QuestieDB Forever database. Do not edit by hand.",
        "local _, ns = ...",
        "",
        "-- [questID] = { requiredLevel, tag (1 Elite / 41 PvP / 62 Raid / 81 Dungeon / 84 Escort / 0 none),",
        "--   objectives, giverKind, giverID, turnInKind, turnInID, xp, {factionID, rep, ...}, {rewardItemIDs},",
        "--   {questIDs that must all be completed first}, {questIDs of which any one must be completed first} }",
        "-- Giver kinds: 1 NPC (ns.NPCs), 2 object (ns.Objects), 3 item (ns.ItemNames).",
        "ns.QuestDetails = {",
    ]
    for qid in sorted(used):
        q = quests[qid]
        objectives = "\n".join(t for t in luatable.as_list(q.get(OBJECTIVES_TEXT)) or [] if isinstance(t, str))
        g_kind, g_id = giver(q.get(STARTED_BY), True)
        e_kind, e_id = giver(q.get(FINISHED_BY), False)
        reps = []
        for pair in luatable.as_list(q.get(REP_REWARD)) or []:
            pair = luatable.as_list(pair)
            if pair and len(pair) >= 2 and pair[0] and pair[1]:
                reps += [pair[0], pair[1]]
        item_ids = sorted(rewards.get(qid, []))
        for item_id in item_ids:
            used_items[item_id] = items[item_id].get(ITEM_NAME)
        # Real requirements from the database (not the looser links used to group storylines).
        pre_all = sorted({p for p in id_list(q.get(PRE_GROUP)) if p in used and p != qid})
        pre_any = sorted({p for p in id_list(q.get(PRE_SINGLE)) if p in used and p != qid})
        quest_xp = (xp.get(qid) or [0, 0])[1] or 0
        lines.append("[%d]={%d,%d,%s,%d,%d,%d,%d,%d,{%s},{%s},{%s},{%s}}," % (
            qid, q.get(REQ_LEVEL) or 0, tag_of(qid, q), lua_str(objectives), g_kind, g_id, e_kind, e_id, quest_xp,
            ",".join(map(str, reps)), ",".join(map(str, item_ids)), ",".join(map(str, pre_all)),
            ",".join(map(str, pre_any))))
    lines.append("}")

    def loc_lua(loc):
        if not loc:
            return "0"
        area, x, y = loc
        used_areas.add(area)
        if x is None:
            return str(area)
        return "%d,%s,%s" % (area, round(x, 1), round(y, 1))

    lines += ["", "-- [npcID] = { name, title or false, areaID, x, y }", "ns.NPCs = {"]
    for nid in sorted(used_npcs):
        name, sub, loc = used_npcs[nid]
        lines.append("[%d]={%s,%s,%s}," % (nid, lua_str(name or "?"), lua_str(sub) if sub else "false", loc_lua(loc)))
    lines += ["}", "", "-- [objectID] = { name, areaID, x, y }", "ns.Objects = {"]
    for oid in sorted(used_objects):
        name, loc = used_objects[oid]
        lines.append("[%d]={%s,%s}," % (oid, lua_str(name or "?"), loc_lua(loc)))
    lines += ["}", "", "-- [itemID] = name (fallback until the client has the item cached)", "ns.ItemNames = {"]
    for iid in sorted(used_items):
        lines.append("[%d]=%s," % (iid, lua_str(used_items[iid] or "?")))
    lines += ["}", "", "-- [areaID] = { zone name, uiMapID } for quest giver locations", "ns.Areas = {"]
    for area in sorted(used_areas):
        ui_map = area_to_map.get(area, 0)
        canonical = map_to_area.get(ui_map) if ui_map else None
        if area in dungeons:
            name = dungeons[area]["name"]
        else:
            name = area_names.get(canonical) or area_names.get(area) or ("Area %d" % area)
        lines.append("[%d]={%s,%d}," % (area, lua_str(name), ui_map))
    lines.append("}")

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("Wrote %s: %d quests, %d NPCs, %d objects, %d items, %d tagged quests" % (
        os.path.relpath(OUTPUT, ROOT), len(used), len(used_npcs), len(used_objects), len(used_items),
        sum(1 for qid in used if tag_of(qid, quests[qid]))))
